const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const multer = require('multer');

const app = express();
const PORT = process.env.PORT || 3000;
const ADMIN_PASSCODE = process.env.ADMIN_PASSCODE || 'glamup2026';

// Paths
const PRODUCTS_JSON_PATH = path.join(__dirname, 'products.json');
const PRODUCTS_JS_PATH = path.join(__dirname, 'products.js');
const UPLOAD_DIR = path.join(__dirname, 'assets', 'uploads');

// Ensure upload directory exists
if (!fs.existsSync(UPLOAD_DIR)) {
    fs.mkdirSync(UPLOAD_DIR, { recursive: true });
}

// Multer storage configuration
const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, UPLOAD_DIR);
    },
    filename: (req, file, cb) => {
        const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
        const ext = path.extname(file.originalname);
        cb(null, 'jewelry-' + uniqueSuffix + ext);
    }
});

const upload = multer({
    storage: storage,
    fileFilter: (req, file, cb) => {
        const filetypes = /jpeg|jpg|png|webp|gif/;
        const extname = filetypes.test(path.extname(file.originalname).toLowerCase());
        const mimetype = filetypes.test(file.mimetype);
        if (mimetype && extname) {
            return cb(null, true);
        }
        cb(new Error('Only image files (jpg, jpeg, png, webp, gif) are allowed!'));
    },
    limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Serve frontend static files
app.use(express.static(__dirname));

// Security middleware for Admin API endpoints
const adminAuth = (req, res, next) => {
    const passcode = req.headers['x-admin-passcode'];
    if (passcode === ADMIN_PASSCODE) {
        next();
    } else {
        res.status(401).json({ error: 'Unauthorized: Invalid admin passcode' });
    }
};

// Helper function to read products data
const readProductsData = () => {
    if (!fs.existsSync(PRODUCTS_JSON_PATH)) {
        return { services: [], jewelry: [] };
    }
    try {
        const fileContent = fs.readFileSync(PRODUCTS_JSON_PATH, 'utf-8');
        return JSON.parse(fileContent);
    } catch (err) {
        console.error('Error reading products.json:', err);
        return { services: [], jewelry: [] };
    }
};

// Helper function to write products data and regenerate products.js
const writeProductsData = (data) => {
    try {
        // 1. Write JSON file
        fs.writeFileSync(PRODUCTS_JSON_PATH, JSON.stringify(data, null, 4), 'utf-8');
        
        // 2. Generate products.js contents
        const productsJsContent = `// Neha's GlamUp Products & Services Catalog
// This file is auto-generated by the backend admin dashboard. Do not edit manually.

const services = ${JSON.stringify(data.services, null, 4)};

const jewelry = ${JSON.stringify(data.jewelry, null, 4)};

// Export for usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { services, jewelry };
}
`;
        fs.writeFileSync(PRODUCTS_JS_PATH, productsJsContent, 'utf-8');
        return true;
    } catch (err) {
        console.error('Error writing products data:', err);
        return false;
    }
};

// Helper to delete an image file if it exists and is an uploaded file
const deleteProductImage = (imagePath) => {
    if (!imagePath) return;
    // Only delete files residing in assets/uploads/ to prevent deleting pre-packaged assets accidentally
    if (imagePath.startsWith('assets/uploads/')) {
        const fullPath = path.join(__dirname, imagePath);
        if (fs.existsSync(fullPath)) {
            try {
                fs.unlinkSync(fullPath);
                console.log(`Deleted unused image: ${imagePath}`);
            } catch (err) {
                console.error(`Failed to delete image: ${fullPath}`, err);
            }
        }
    }
};

// --- API Endpoints ---

// 1. Validate passcode
app.post('/api/auth/validate', (req, res) => {
    const { passcode } = req.body;
    if (passcode === ADMIN_PASSCODE) {
        res.json({ success: true, message: 'Authenticated successfully' });
    } else {
        res.status(401).json({ success: false, error: 'Invalid passcode' });
    }
});

// 2. Read all products (Public endpoint)
app.get('/api/products', (req, res) => {
    const data = readProductsData();
    res.json(data);
});

// 3. Create a product (Admin only)
app.post('/api/products', adminAuth, upload.single('image'), (req, res) => {
    try {
        const { type, name, title, category, price, originalPrice, description, icon, isKorean } = req.body;
        const data = readProductsData();
        
        if (type === 'jewelry') {
            if (!name || !category) {
                if (req.file) deleteProductImage(path.join('assets/uploads', req.file.filename));
                return res.status(400).json({ error: 'Name and Category are required for jewelry' });
            }
            if (!req.file) {
                return res.status(400).json({ error: 'An image file upload is required for new jewelry' });
            }

            const imagePath = `assets/uploads/${req.file.filename}`;
            const id = 'jewelry-' + Date.now();
            
            const newJewelry = {
                id,
                name,
                category, // 'renting' or 'selling'
                price: price || '',
                originalPrice: originalPrice || '',
                description: description || '',
                image: imagePath,
                isKorean: isKorean === 'true'
            };
            
            data.jewelry.push(newJewelry);
            if (writeProductsData(data)) {
                res.status(201).json({ success: true, item: newJewelry });
            } else {
                deleteProductImage(imagePath);
                res.status(500).json({ error: 'Database write error' });
            }

        } else if (type === 'service') {
            if (!title || !category || !icon) {
                return res.status(400).json({ error: 'Title, Category, and Icon are required for services' });
            }
            
            const id = 'service-' + Date.now();
            const newService = {
                id,
                title,
                category,
                description: description || '',
                icon,
                type: category.toLowerCase().includes('makeup') || category.toLowerCase().includes('bridal') ? 'makeup' : 'beautician'
            };
            
            data.services.push(newService);
            if (writeProductsData(data)) {
                res.status(201).json({ success: true, item: newService });
            } else {
                res.status(500).json({ error: 'Database write error' });
            }
        } else {
            if (req.file) deleteProductImage(path.join('assets/uploads', req.file.filename));
            res.status(400).json({ error: 'Invalid product type. Must be jewelry or service.' });
        }
    } catch (err) {
        console.error('Error creating product:', err);
        if (req.file) deleteProductImage(path.join('assets/uploads', req.file.filename));
        res.status(500).json({ error: err.message });
    }
});

// 4. Update a product (Admin only)
app.put('/api/products/:id', adminAuth, upload.single('image'), (req, res) => {
    try {
        const { id } = req.params;
        const { type, name, title, category, price, originalPrice, description, icon, isKorean } = req.body;
        const data = readProductsData();
        
        let found = false;
        
        if (type === 'jewelry') {
            const index = data.jewelry.findIndex(item => item.id === id);
            if (index !== -1) {
                found = true;
                const oldItem = data.jewelry[index];
                let imagePath = oldItem.image;
                
                // If a new image was uploaded
                if (req.file) {
                    // Delete old upload if it exists
                    deleteProductImage(oldItem.image);
                    imagePath = `assets/uploads/${req.file.filename}`;
                }
                
                data.jewelry[index] = {
                    ...oldItem,
                    name: name || oldItem.name,
                    category: category || oldItem.category,
                    price: price !== undefined ? price : oldItem.price,
                    originalPrice: originalPrice !== undefined ? originalPrice : oldItem.originalPrice,
                    description: description !== undefined ? description : oldItem.description,
                    image: imagePath,
                    isKorean: isKorean !== undefined ? (isKorean === 'true') : oldItem.isKorean
                };
                
                if (writeProductsData(data)) {
                    res.json({ success: true, item: data.jewelry[index] });
                } else {
                    if (req.file) deleteProductImage(imagePath);
                    res.status(500).json({ error: 'Database write error' });
                }
            }
        } else if (type === 'service') {
            const index = data.services.findIndex(item => item.id === id);
            if (index !== -1) {
                found = true;
                const oldItem = data.services[index];
                
                data.services[index] = {
                    ...oldItem,
                    title: title || oldItem.title,
                    category: category || oldItem.category,
                    description: description !== undefined ? description : oldItem.description,
                    icon: icon || oldItem.icon,
                    type: category ? (category.toLowerCase().includes('makeup') || category.toLowerCase().includes('bridal') ? 'makeup' : 'beautician') : oldItem.type
                };
                
                if (writeProductsData(data)) {
                    res.json({ success: true, item: data.services[index] });
                } else {
                    res.status(500).json({ error: 'Database write error' });
                }
            }
        }
        
        if (!found) {
            if (req.file) deleteProductImage(path.join('assets/uploads', req.file.filename));
            res.status(404).json({ error: `Product with ID ${id} not found.` });
        }
    } catch (err) {
        console.error('Error updating product:', err);
        if (req.file) deleteProductImage(path.join('assets/uploads', req.file.filename));
        res.status(500).json({ error: err.message });
    }
});

// 5. Delete a product (Admin only)
app.delete('/api/products/:id', adminAuth, (req, res) => {
    try {
        const { id } = req.params;
        const data = readProductsData();
        
        let found = false;
        
        // Try searching in jewelry
        const jewelryIndex = data.jewelry.findIndex(item => item.id === id);
        if (jewelryIndex !== -1) {
            found = true;
            const item = data.jewelry[jewelryIndex];
            // Delete image file from disk
            deleteProductImage(item.image);
            data.jewelry.splice(jewelryIndex, 1);
        } else {
            // Try searching in services
            const serviceIndex = data.services.findIndex(item => item.id === id);
            if (serviceIndex !== -1) {
                found = true;
                data.services.splice(serviceIndex, 1);
            }
        }
        
        if (found) {
            if (writeProductsData(data)) {
                res.json({ success: true, message: `Successfully deleted product: ${id}` });
            } else {
                res.status(500).json({ error: 'Database write error' });
            }
        } else {
            res.status(404).json({ error: `Product with ID ${id} not found.` });
        }
    } catch (err) {
        console.error('Error deleting product:', err);
        res.status(500).json({ error: err.message });
    }
});

// Start Server
app.listen(PORT, () => {
    console.log(`========================================`);
    console.log(`Neha's GlamUp Admin Backend is running!`);
    console.log(`Server URL: http://localhost:${PORT}`);
    console.log(`Admin panel: http://localhost:${PORT}/admin.html`);
    console.log(`========================================`);
});
