const fs = require('fs');
const path = require('path');

const PRODUCTS_JSON_PATH = path.join(__dirname, 'products.json');
const PRODUCTS_JS_PATH = path.join(__dirname, 'products.js');
const FRONTEND_PRODUCTS_JS_PATH = path.join(__dirname, '..', 'products.js');

if (!fs.existsSync(PRODUCTS_JSON_PATH)) {
    console.error('products.json not found!');
    process.exit(1);
}

const fileContent = fs.readFileSync(PRODUCTS_JSON_PATH, 'utf-8');
const data = JSON.parse(fileContent);

console.log('Original jewelry items count:', data.jewelry.length);

data.jewelry.forEach((item) => {
    const name = (item.name || '').toLowerCase();
    const desc = (item.description || '').toLowerCase();
    const oldCat = item.category;

    if (item.category === 'renting' || name.includes('bridal') || name.includes('haram') || name.includes('guttapusalu') || desc.includes('rent')) {
        item.category = 'rented jewelry';
    } else if (name.includes('earring') || name.includes('stud') || name.includes('hoop') || name.includes('cuff') || name.includes('studs') || name.includes('hoops')) {
        item.category = 'korean earrings';
    } else if (name.includes('bracelet') || name.includes('bangles') || name.includes('bangle') || name.includes('cuff')) {
        item.category = 'bracelet';
    } else if (name.includes('anklet')) {
        item.category = 'anklet';
    } else if (name.includes('nosepin') || name.includes('nose pin') || name.includes('nosepins') || name.includes('nose pins')) {
        item.category = 'nose pins';
    } else if (name.includes('hairpin') || name.includes('hair pin') || name.includes('tiara') || name.includes('bun pin') || name.includes('hair tiara') || name.includes('hair pins') || name.includes('bun pins')) {
        item.category = 'hair accessories';
    } else if (name.includes('buggadi')) {
        item.category = 'buggadi';
    } else if (name.includes('kids') || name.includes('child') || name.includes('kid')) {
        item.category = 'chains for kids';
    } else if (name.includes('pendant') || name.includes('choker') || name.includes('necklace') || name.includes('brooch') || name.includes('ring') || name.includes('chain')) {
        item.category = 'choker'; // Fallback for neckpieces/rings
    } else {
        // Fallback default
        item.category = item.isKorean ? 'korean earrings' : 'choker';
    }

    console.log(`Mapped: "${item.name}" -> ${item.category} (was: ${oldCat})`);
});

// Save the updated JSON file
fs.writeFileSync(PRODUCTS_JSON_PATH, JSON.stringify(data, null, 4), 'utf-8');
console.log('Saved updated products.json');

// Re-generate products.js files
const productsJsContent = `// Neha's GlamUp Products & Services Catalog
// This file is auto-generated by the backend admin dashboard. Do not edit manually.

const services = ${JSON.stringify(data.services, null, 4)};

const jewelry = ${JSON.stringify(data.jewelry, null, 4)};

const jewelryCategories = ${JSON.stringify(data.jewelryCategories || [], null, 4)};

// Export for usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { services, jewelry, jewelryCategories };
}
`;

fs.writeFileSync(PRODUCTS_JS_PATH, productsJsContent, 'utf-8');
console.log('Saved backend/products.js');

try {
    fs.writeFileSync(FRONTEND_PRODUCTS_JS_PATH, productsJsContent, 'utf-8');
    console.log('Saved root products.js');
} catch (err) {
    console.error('Could not save root products.js:', err.message);
}

console.log('Migration completed successfully!');
