// Neha's GlamUp Products & Services Catalog
// This file is auto-generated by the backend admin dashboard. Do not edit manually.

const services = [
    {
        "id": "bridal-makeup",
        "title": "Bridal Makeup",
        "category": "Bridal & Ceremonial",
        "description": "Premium, long-lasting bridal makeover customized to match your wedding attire, jewelry, and personal style. Includes standard draping and hair styling.",
        "icon": "👑",
        "type": "makeup"
    },
    {
        "id": "engagement-makeup",
        "title": "Engagement Makeup",
        "category": "Bridal & Ceremonial",
        "description": "Elegant, radiant, and dewy makeup look designed to make you glow on your ring ceremony. Complemented by sophisticated hair styling.",
        "icon": "💍",
        "type": "makeup"
    },
    {
        "id": "reception-makeup",
        "title": "Reception Makeup",
        "category": "Bridal & Ceremonial",
        "description": "High-glam, sophisticated, and camera-ready evening makeup designed to stand out under reception lighting.",
        "icon": "✨",
        "type": "makeup"
    },
    {
        "id": "haldi-makeup",
        "title": "Haldi & Mehendi Makeup",
        "category": "Pre-Wedding",
        "description": "Vibrant, fresh, and lightweight makeup tailored for daytime rituals. Sweat-proof and smudge-proof for stress-free celebrations.",
        "icon": "💛",
        "type": "makeup"
    },
    {
        "id": "party-makeup",
        "title": "Party Makeup",
        "category": "Occasions",
        "description": "Customized makeover ranging from subtle and natural to bold and dramatic, perfect for party guests, cocktail events, or festivals.",
        "icon": "💄",
        "type": "makeup"
    },
    {
        "id": "airbrush-makeup",
        "title": "Airbrush Makeup",
        "category": "Specialized Techniques",
        "description": "Ultra-flawless, lightweight, and water-resistant makeup applied using professional airbrushing for a seamless, second-skin finish.",
        "icon": "💨",
        "type": "makeup"
    },
    {
        "id": "hd-makeup",
        "title": "HD Makeup",
        "category": "Specialized Techniques",
        "description": "High-definition makeup using light-diffusing products that look completely natural in person and stunning in 4K photography and videography.",
        "icon": "📸",
        "type": "makeup"
    },
    {
        "id": "waterproof-makeup",
        "title": "Waterproof & Sweat-Proof",
        "category": "Specialized Techniques",
        "description": "Advanced long-wear makeup formulas locked in to withstand humidity, sweat, and tears. Ideal for long ceremonies and Hyderabad summers.",
        "icon": "☔",
        "type": "makeup"
    },
    {
        "id": "pre-wedding-makeup",
        "title": "Pre-Wedding Shoot Makeup",
        "category": "Pre-Wedding",
        "description": "Photogenic makeup looks tailored for outdoor shoots, matching different outfits and concepts with camera-friendly contouring.",
        "icon": "📹",
        "type": "makeup"
    },
    {
        "id": "customized-makeup",
        "title": "Customized Makeup",
        "category": "Occasions",
        "description": "A tailored makeup experience designed after a personal consultation to perfectly fit your skin type, tone, and specific event theme.",
        "icon": "🌸",
        "type": "makeup"
    },
    {
        "id": "saree-draping",
        "title": "Saree Draping & Pleating",
        "category": "Styling Services",
        "description": "Professional draping for all saree types (Kanjeevaram, Silk, Georgette, Lehenga style) with perfect, secure pleating that lasts all day.",
        "icon": "👘",
        "type": "makeup"
    },
    {
        "id": "hairstyles",
        "title": "Professional Hairstyles",
        "category": "Styling Services",
        "description": "From classic bridal buns and intricate braids (Jada) to modern curls, waves, and extensions, styled to perfectly complement your look.",
        "icon": "💇",
        "type": "makeup"
    },
    {
        "id": "mehendi-bridal",
        "title": "Bridal Mehendi",
        "category": "Mehendi Designs",
        "description": "Full hands and feet traditional intricate bridal henna designs featuring elegant custom motifs, portraits, and dark-staining finish.",
        "icon": "🌿",
        "type": "mehendi"
    },
    {
        "id": "mehendi-arabic",
        "title": "Arabic Mehendi",
        "category": "Mehendi Designs",
        "description": "Bold, shaded floral patterns and flowing vines with thick outlines. Elegant and perfect for festivals or bridesmaids.",
        "icon": "🌸",
        "type": "mehendi"
    },
    {
        "id": "mehendi-khafife",
        "title": "Khafife Mehendi",
        "category": "Mehendi Designs",
        "description": "Ultra-thin, delicate, and symmetric geometric Arabic patterns that look like exquisite lace on the skin.",
        "icon": "✨",
        "type": "mehendi"
    },
    {
        "id": "mehendi-indo-western",
        "title": "Indo-Western Fusion",
        "category": "Mehendi Designs",
        "description": "A gorgeous blend of traditional Indian paisley motifs and spacious modern negative space Arabic layouts.",
        "icon": "💫",
        "type": "mehendi"
    },
    {
        "id": "mehendi-mandala",
        "title": "Mandala Mehendi",
        "category": "Mehendi Designs",
        "description": "Beautiful traditional circular mandala motifs placed at the center of palms and back of hands with decorative finger patterns.",
        "icon": "🌀",
        "type": "mehendi"
    },
    {
        "id": "mehendi-baby-shower",
        "title": "Baby Shower Special",
        "category": "Mehendi Designs",
        "description": "Customized henna patterns depicting motherhood, cradles, and baby motifs on palms celebrating upcoming motherhood.",
        "icon": "👶",
        "type": "mehendi"
    },
    {
        "id": "mehendi-guest",
        "title": "Guest & Family Henna",
        "category": "Mehendi Designs",
        "description": "Quick, elegant, and stylish single-strip or palm henna designs suited for wedding guests, bridesmaids, and kids.",
        "icon": "💅",
        "type": "mehendi"
    },
    {
        "id": "hydrafacial-glow",
        "title": "HydraFacial Glow",
        "category": "Skincare & Salon",
        "description": "Premium deep-cleansing, exfoliation, and intense skin hydration therapy. *Beauty from inner with flawless glam.*",
        "icon": "💆‍♀️",
        "type": "beautician"
    },
    {
        "id": "gold-facial",
        "title": "Gold Luxury Facial",
        "category": "Skincare & Salon",
        "description": "Brighten and rejuvenate your skin with a luxury gold facial. Ideal for brides and guests seeking a flawless bridal glow.",
        "icon": "✨",
        "type": "beautician"
    },
    {
        "id": "diamond-facial",
        "title": "Diamond Radiance Facial",
        "category": "Skincare & Salon",
        "description": "Diamond dust polish facial designed for deep exfoliation, skin tightening, and an ultra-brilliant flawless finish.",
        "icon": "💎",
        "type": "beautician"
    },
    {
        "id": "detan-brightening",
        "title": "De-Tan & Skin Brightening",
        "category": "Skincare & Salon",
        "description": "Revive your natural complexion and clear sun tanning using professional, safe, and herbal organic de-tan formulations.",
        "icon": "🌿",
        "type": "beautician"
    },
    {
        "id": "oiling-hair",
        "title": "Oiling Hair Treatment",
        "category": "Skincare & Salon",
        "description": "Relaxing warm oil massage therapy for your scalp and hair using premium herbal oils. Nourishes roots, promotes growth, and adds natural shine.",
        "icon": "🧴",
        "type": "beautician"
    },
    {
        "id": "henna-services",
        "title": "Henna Services",
        "category": "Skincare & Salon",
        "description": "Beautiful, rich henna application for hands and feet. From traditional bridal patterns to trendy Arabic and Indo-Western designs with long-lasting color.",
        "icon": "🌿",
        "type": "beautician"
    }
];

const jewelry = [
    {
        "id": "royal-kundan-set",
        "name": "Royal Kundan Bridal Set",
        "category": "renting",
        "price": "Rent: ₹2,499 / day",
        "description": "Premium gold-plated Kundan choker necklace embellished with green glass beads, matching jhumkas, and an elegant maang tikka.",
        "image": "assets/jewelry_kundan_set.jpg",
        "isKorean": false,
        "originalPrice": ""
    },
    {
        "id": "temple-gold-haram",
        "name": "Temple Gold Long Haram",
        "category": "renting",
        "price": "Rent: ₹1,999 / day",
        "description": "Traditional South Indian long necklace featuring intricate carvings of Goddess Lakshmi, bordered by red rubies and seed pearls.",
        "image": "assets/jewelry_temple_haram.jpg",
        "isKorean": false,
        "originalPrice": ""
    },
    {
        "id": "antique-guttapusalu",
        "name": "Antique Guttapusalu Choker",
        "category": "renting",
        "price": "Rent: ₹1,799 / day",
        "description": "Stunning heritage choker loaded with premium pearl clusters (guttapusalu) and rubies, giving an authentic royal look.",
        "image": "assets/jewelry_guttapusalu.jpg",
        "isKorean": false,
        "originalPrice": ""
    },
    {
        "id": "korean-jewelry-1",
        "name": "Blue Stone Square Earrings",
        "category": "selling",
        "price": "249",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223756.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-2",
        "name": "Korean Blossom Black Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223831.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-3",
        "name": "Minimalist Navy Blue Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223931.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-4",
        "name": "Sparkling Crystal Hoop Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224006.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-5",
        "name": "Gold Drop Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224018.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-6",
        "name": "Vintage Gold Drop Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224043.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-7",
        "name": "Korean Loop Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224115.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-8",
        "name": "Elegant Baby Pink Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224136.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-9",
        "name": "Bohemian Tassel Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224153.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-10",
        "name": "Sleek Geometric Violet Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224235.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-11",
        "name": "Classic Cubic Zirconia Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224252.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-12",
        "name": "Korean Crystal Leaf Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224302.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-13",
        "name": "Dainty Starburst Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224322.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-14",
        "name": "Textured Gold Dome Stud Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224342.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-16",
        "name": "Luxury Pearl Cluster Buggadi",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224551.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-17",
        "name": "Black Luxury Bracelet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_224626.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-18",
        "name": "Elegant Floral Nosepins/Earrings",
        "category": "selling",
        "price": "100",
        "description": "eaturing premium finishes and can be used in 2 ways. 100 per pair (2 pieces)",
        "image": "assets/korean/20260613_225134.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-19",
        "name": "Press On Nosepins",
        "category": "selling",
        "price": "30",
        "description": "Press on Nosepins in 3 colors",
        "image": "assets/korean/20260613_225303.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-20",
        "name": "Sparkling Tear-drop Pendant",
        "category": "selling",
        "price": "100",
        "description": "Middle nose pin",
        "image": "assets/korean/20260613_225441.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-21",
        "name": "White Gold Floral Bun pins",
        "category": "selling",
        "price": "12",
        "description": "Unique hair jewelry piece.",
        "image": "assets/korean/20260613_233627.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-22",
        "name": "Dainty Butterfly Bun Pins",
        "category": "selling",
        "price": "15",
        "description": "Bun Pins for hair",
        "image": "assets/korean/20260613_233739.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-23",
        "name": "Vintage Filigree Hair Tiara",
        "category": "selling",
        "price": "150",
        "description": "Vintage Filigree Hair Tiara",
        "image": "assets/korean/20260613_233826.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-24",
        "name": "Shell Moonstone Bun Pins",
        "category": "selling",
        "price": "10",
        "description": "Curly Hair accessories",
        "image": "assets/korean/20260613_234245.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-25",
        "name": "Glistening Pearl Hair Pins",
        "category": "selling",
        "price": "10",
        "description": "Curly Hair accessories",
        "image": "assets/korean/20260613_234411.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-26",
        "name": "Delicate Floral Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_234650.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-27",
        "name": "Modern Chevron Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_234819.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-28",
        "name": "Luxury Solitaire Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_235128.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-29",
        "name": "Korean Multi-stone Bracelet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_235834.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-30",
        "name": "Elegant Velvet Ribbon Choker",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_235907.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-31",
        "name": "Sparkling Constellation Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_235928.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-32",
        "name": "Dainty Chain Link Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_235946.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-33",
        "name": "Korean Tassel Drop Necklace",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/InShot_20260613_225035183.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-34",
        "name": "Pastel Gemstone Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221017.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-35",
        "name": "Golden Leaf Drop Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221145.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-36",
        "name": "Crystal Vine Pendant",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221200.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-37",
        "name": "Rose Gold Infinity Bracelet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221227.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-38",
        "name": "Pearl Cascade Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221344.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-39",
        "name": "Diamond Cluster Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221356.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-40",
        "name": "Sapphire Chain Necklace",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221525.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-41",
        "name": "Celestial Star Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221638.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-42",
        "name": "Vintage Pearl Brooch",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221716.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-43",
        "name": "Twisted Gold Hoop Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221745.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-44",
        "name": "Amethyst Drop Pendant",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221807.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-45",
        "name": "Floral Pearl Statement Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221817.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-47",
        "name": "Baroque Pearl Necklace",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221852.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-48",
        "name": "Crystal Heart Pendant",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221858.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-49",
        "name": "Korean Turquoise Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_221951.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-50",
        "name": "Emerald Teardrop Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222007.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-51",
        "name": "Layered Chain Bracelet Set",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222019.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-52",
        "name": "Filigree Gold Ear Cuff",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222035.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-53",
        "name": "Opal Aurora Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222138.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-54",
        "name": "Dainty Sunburst Pendant",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222219.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-55",
        "name": "Crystal Butterfly Hairpin",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222249.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-56",
        "name": "Rose Quartz Bead Bracelet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222345.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-57",
        "name": "Polished Silver Cuff Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222434.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-58",
        "name": "Luxe Pearl Anklet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222659.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-59",
        "name": "Matte Gold Cuff Bracelet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_222925.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-60",
        "name": "Minimalist Wave Earrings",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223151.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-61",
        "name": "Vintage Charm Necklace",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223206.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-62",
        "name": "Korean Jade Studs",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223528.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-63",
        "name": "Frosted Glass Pendant",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223536.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-64",
        "name": "Spiral Gold Wire Ring",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223636.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-65",
        "name": "Petal Drop Choker",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223710.jpg",
        "isKorean": true,
        "originalPrice": "500"
    },
    {
        "id": "korean-jewelry-66",
        "name": "Korean Crystal Chain Bracelet",
        "category": "selling",
        "price": "250",
        "description": "Exquisite, unique, and imported Korean jewelry piece. Featuring premium finishes and elegant design.",
        "image": "assets/korean/20260613_223724.jpg",
        "isKorean": true,
        "originalPrice": "500"
    }
];

const jewelryCategories = [
    "bracelet",
    "choker",
    "anklet",
    "nose pins",
    "korean earrings",
    "hair accessories",
    "buggadi",
    "chains for kids",
    "rented jewelry"
];

// Export for usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { services, jewelry, jewelryCategories };
}
